export const mealTypes = [
	'breakfast',
	'mainCourse',
	'appetizer',
	'dinner',
	'dessert',
];

export const dietaryTypes = ['vegan', 'vegetarian', 'glutenFree', 'lowCalorie'];

export const nutrientTypes = ['protein', 'carbohydrate', 'fat'];

export const nutrientCardItems = [
	{ key: 'calories', icon: 'Calories', unit: 'kcal' },
	{ key: 'protein', icon: 'Protein', unit: 'g' },
	{ key: 'carbohydrate', icon: 'Carbs', unit: 'g' },
	{ key: 'fat', icon: 'Fat', unit: 'g' },
];

export const fridgeCategories = [
	{
		id: 1,
		category: 'meat',
		products: [
			{ id: '1-1', name: 'chicken' },
			{ id: '1-2', name: 'beef' },
			{ id: '1-3', name: 'pork' },
			{ id: '1-4', name: 'fish' },
			{ id: '1-5', name: 'salmon' },
			{ id: '1-6', name: 'shrimp' },
			{ id: '1-7', name: 'lamb' },
			{ id: '1-8', name: 'turkey' },
			{ id: '1-9', name: 'ground beef' },
			{ id: '1-10', name: 'sausage' },
			{ id: '1-11', name: 'bacon' },
			{ id: '1-12', name: 'ham' },
		],
	},
	{
		id: 2,
		category: 'dairy',
		products: [
			{ id: '2-1', name: 'milk' },
			{ id: '2-2', name: 'cheese' },
			{ id: '2-3', name: 'yogurt' },
			{ id: '2-4', name: 'butter' },
			{ id: '2-5', name: 'cream' },
			{ id: '2-6', name: 'sour cream' },
			{ id: '2-7', name: 'cottage cheese' },
			{ id: '2-8', name: 'cheddar' },
			{ id: '2-9', name: 'mozzarella' },
			{ id: '2-10', name: 'parmesan' },
			{ id: '2-11', name: 'feta' },
		],
	},
	{
		id: 3,
		category: 'vegetables',
		products: [
			{ id: '3-1', name: 'tomato' },
			{ id: '3-2', name: 'cucumber' },
			{ id: '3-3', name: 'carrot' },
			{ id: '3-4', name: 'onion' },
			{ id: '3-5', name: 'potato' },
			{ id: '3-6', name: 'broccoli' },
			{ id: '3-7', name: 'bell pepper' },
			{ id: '3-8', name: 'lettuce' },
			{ id: '3-9', name: 'spinach' },
			{ id: '3-10', name: 'mushroom' },
			{ id: '3-11', name: 'eggplant' },
			{ id: '3-12', name: 'garlic' },
			{ id: '3-13', name: 'zucchini' },
			{ id: '3-14', name: 'corn' },
			{ id: '3-15', name: 'peas' },
			{ id: '3-16', name: 'green beans' },
			{ id: '3-17', name: 'cauliflower' },
			{ id: '3-18', name: 'celery' },
			{ id: '3-19', name: 'cabbage' },
			{ id: '3-20', name: 'leek' },
		],
	},
	{
		id: 4,
		category: 'fruits',
		products: [
			{ id: '4-1', name: 'apple' },
			{ id: '4-2', name: 'banana' },
			{ id: '4-3', name: 'orange' },
			{ id: '4-4', name: 'strawberry' },
			{ id: '4-5', name: 'grape' },
			{ id: '4-6', name: 'lemon' },
			{ id: '4-7', name: 'lime' },
			{ id: '4-8', name: 'peach' },
			{ id: '4-9', name: 'cherry' },
			{ id: '4-10', name: 'pineapple' },
			{ id: '4-11', name: 'avocado' },
			{ id: '4-12', name: 'berries' },
			{ id: '4-13', name: 'kiwi' },
		],
	},
	{
		id: 5,
		category: 'sauces',
		products: [
			{ id: '5-1', name: 'ketchup' },
			{ id: '5-2', name: 'mayonnaise' },
			{ id: '5-3', name: 'mustard' },
			{ id: '5-4', name: 'soy sauce' },
			{ id: '5-5', name: 'hot sauce' },
			{ id: '5-6', name: 'bbq sauce' },
			{ id: '5-7', name: 'tomato sauce' },
			{ id: '5-8', name: 'salsa' },
			{ id: '5-9', name: 'pesto' },
			{ id: '5-10', name: 'worcestershire sauce' },
			{ id: '5-11', name: 'tahini' },
			{ id: '5-12', name: 'hummus' },
		],
	},
	{
		id: 6,
		category: 'sweeteners',
		products: [
			{ id: '6-1', name: 'honey' },
			{ id: '6-2', name: 'maple syrup' },
			{ id: '6-3', name: 'jam' },
			{ id: '6-4', name: 'chocolate spread' },
			{ id: '6-5', name: 'peanut butter' },
			{ id: '6-6', name: 'jelly' },
		],
	},
	{
		id: 7,
		category: 'eggs',
		products: [
			{ id: '7-1', name: 'egg' },
			{ id: '7-2', name: 'quail egg' },
			{ id: '7-3', name: 'egg white' },
			{ id: '7-4', name: 'egg yolk' },
		],
	},
	{
		id: 8,
		category: 'legumes',
		products: [
			{ id: '8-1', name: 'beans' },
			{ id: '8-2', name: 'red lentils' },
			{ id: '8-3', name: 'green lentils' },
			{ id: '8-4', name: 'chickpeas' },
			{ id: '8-5', name: 'black beans' },
			{ id: '8-6', name: 'kidney beans' },
			{ id: '8-7', name: 'split peas' },
		],
	},
	{
		id: 9,
		category: 'grains',
		products: [
			{ id: '9-1', name: 'rice' },
			{ id: '9-2', name: 'pasta' },
			{ id: '9-3', name: 'bulgur' },
			{ id: '9-4', name: 'quinoa' },
			{ id: '9-5', name: 'oats' },
			{ id: '9-6', name: 'couscous' },
			{ id: '9-7', name: 'bread' },
			{ id: '9-8', name: 'tortilla' },
			{ id: '9-9', name: 'pita bread' },
			{ id: '9-10', name: 'breadcrumbs' },
			{ id: '9-11', name: 'brown rice' },
			{ id: '9-12', name: 'barley' },
		],
	},
	{
		id: 10,
		category: 'baking',
		products: [
			{ id: '10-1', name: 'flour' },
			{ id: '10-2', name: 'sugar' },
			{ id: '10-3', name: 'brown sugar' },
			{ id: '10-4', name: 'baking powder' },
			{ id: '10-5', name: 'baking soda' },
			{ id: '10-6', name: 'vanilla extract' },
			{ id: '10-7', name: 'cocoa powder' },
			{ id: '10-8', name: 'chocolate chips' },
			{ id: '10-9', name: 'chocolate bar' },
			{ id: '10-10', name: 'yeast' },
			{ id: '10-11', name: 'cornstarch' },
			{ id: '10-12', name: 'powdered sugar' },
		],
	},
	{
		id: 11,
		category: 'nuts',
		products: [
			{ id: '11-1', name: 'peanuts' },
			{ id: '11-2', name: 'almonds' },
			{ id: '11-3', name: 'walnuts' },
			{ id: '11-4', name: 'hazelnuts' },
			{ id: '11-5', name: 'pistachios' },
			{ id: '11-6', name: 'cashews' },
			{ id: '11-7', name: 'pine nuts' },
			{ id: '11-8', name: 'chia seeds' },
			{ id: '11-9', name: 'flax seeds' },
			{ id: '11-10', name: 'sesame seeds' },
			{ id: '11-11', name: 'sunflower seeds' },
			{ id: '11-12', name: 'pumpkin seeds' },
		],
	},
	{
		id: 12,
		category: 'spices',
		products: [
			{ id: '12-1', name: 'salt' },
			{ id: '12-2', name: 'black pepper' },
			{ id: '12-3', name: 'cumin' },
			{ id: '12-4', name: 'oregano' },
			{ id: '12-5', name: 'cinnamon' },
			{ id: '12-6', name: 'thyme' },
			{ id: '12-7', name: 'paprika' },
			{ id: '12-8', name: 'cayenne pepper' },
			{ id: '12-9', name: 'chili powder' },
			{ id: '12-10', name: 'curry powder' },
			{ id: '12-11', name: 'bay leaf' },
			{ id: '12-12', name: 'basil' },
			{ id: '12-13', name: 'rosemary' },
			{ id: '12-14', name: 'sage' },
			{ id: '12-15', name: 'mint' },
			{ id: '12-16', name: 'ginger' },
			{ id: '12-17', name: 'turmeric' },
			{ id: '12-18', name: 'cardamom' },
			{ id: '12-19', name: 'cloves' },
			{ id: '12-20', name: 'nutmeg' },
		],
	},
	{
		id: 13,
		category: 'oils',
		products: [
			{ id: '13-1', name: 'olive oil' },
			{ id: '13-2', name: 'vegetable oil' },
			{ id: '13-3', name: 'sunflower oil' },
			{ id: '13-4', name: 'coconut oil' },
			{ id: '13-5', name: 'sesame oil' },
			{ id: '13-6', name: 'vinegar' },
			{ id: '13-7', name: 'balsamic vinegar' },
			{ id: '13-8', name: 'apple cider vinegar' },
			{ id: '13-9', name: 'rice vinegar' },
		],
	},
	{
		id: 14,
		category: 'herbs',
		products: [
			{ id: '14-1', name: 'parsley' },
			{ id: '14-2', name: 'cilantro' },
			{ id: '14-3', name: 'dill' },
			{ id: '14-4', name: 'green onion' },
			{ id: '14-5', name: 'chives' },
			{ id: '14-6', name: 'arugula' },
			{ id: '14-7', name: 'basil leaves' },
			{ id: '14-8', name: 'mint leaves' },
		],
	},
];
